PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sdm: <http://example.org/sdm#>

SELECT ?property
WHERE {
  {
    ?property rdfs:domain sdm:Conference.
  } 
# The following block of code is optional because in our schema, no property is related to Journal
# --------------------------------------
UNION {
    ?property rdfs:domain sdm:Journal.
  }
# --------------------------------------
}