PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sdm: <http://example.org/sdm#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?paper
WHERE {
	?v sdm:venueRelatedTo ?area .
    ?v rdf:type sdm:Conference . 
    ?v sdm:hasPublished ?pub .
    ?area sdm:hasTopicName "Database" .
    ?paper sdm:publishedIn ?pub . 
    ?paper sdm:hasAuthor ?author .
    ?paper sdm:paperTitle ?title . 
    ?author sdm:hasPersonName "Neeraj Sharma"  
}