PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sdm: <http://example.org/sdm#>

SELECT DISTINCT ?property
WHERE {
  {
    ?property rdfs:domain sdm:Conference.
  }
  UNION
  {
    sdm:Conference rdfs:subClassOf* ?superclass.
    ?property rdfs:domain ?superclass.
  }
# The following block of code is optional because in our schema, no property is related to Journal
# --------------------------------------
  UNION
  {
    ?property rdfs:domain sdm:Journal.
  }
# --------------------------------------
  UNION
  {
    sdm:Journal rdfs:subClassOf* ?superclass.
    ?property rdfs:domain ?superclass.
  }
}